app:
  secret_key: 'your-secret-key-here'
  debug: True
  host: '0.0.0.0'
  port: 5000

database:
  mysql:
    host: '127.0.0.1'
    port: 3306
    user: 'root'
    password: '123456'
    database: 'jxkh'
